global:
   scrape_interval: 15s
   evaluation_interval: 15s
   external_labels:
     cluster: ap-south2
     replica: 0

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
      - targets: ['prometheus-0-apsouth2:9092']
   - job_name: 'sidecar'
     static_configs:
      - targets: ['sidecar-2:19090']

