global:
   scrape_interval: 15s
   evaluation_interval: 15s
   external_labels:
     cluster: ap-south1
     replica: 0

rule_files:
  - "recording-rule.yml"

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
      - targets: ['prometheus-0-apsouth1:9090', 'prometheus-1-apsouth1:9091', 'host.docker.internal:8080', 'host.docker.internal:9374'] # last one is additional (cc: https://github.com/SuperQ/smokeping_prober :)
   - job_name: 'sidecar'
     static_configs:
      - targets: ['sidecar-0:19091', 'sidecar-1:19092']
   - job_name: 'querier'
     static_configs:
      - targets: ['querier-main:29090']
   - job_name: 'store'
     static_configs:
      - targets: ['store-gateway:19094']
   - job_name: 'compact'
     static_configs:
      - targets: ['thanos-compact:19095']

