global:
   scrape_interval: 15s
   evaluation_interval: 15s
   external_labels:
     cluster: ap-south2
     replica: 0

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
      - targets: ['prometheus-0-apsouth2:9092']
   - job_name: 'sidecar'
     static_configs:
      - targets: ['sidecar-2:19090']
   - job_name: 'receiver'
     static_configs:
      - targets: ['thanos-receive:10908']
remote_write:
   - url: "http://thanos-receive:10908/api/v1/receive"
