global:
   scrape_interval: 15s
   evaluation_interval: 15s
   external_labels:
     cluster: ap-south1
     replica: 0

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
      - targets: ['prometheus-0-apsouth1:9090', 'prometheus-1-apsouth1:9091']
   - job_name: 'sidecar'
     static_configs:
      - targets: ['sidecar-0:19091', 'sidecar-1:19092']

